// Code generated by MockGen. DO NOT EDIT.
// Source: blockchain/transact_gateway.go

// Package mock_blockchain is a generated GoMock package.
package mock_blockchain

import (
	context "context"
	big "math/big"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/openweb3-io/crosschain/types"
)

// MockTransactGateway is a mock of TransactGateway interface.
type MockTransactGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTransactGatewayMockRecorder
}

// MockTransactGatewayMockRecorder is the mock recorder for MockTransactGateway.
type MockTransactGatewayMockRecorder struct {
	mock *MockTransactGateway
}

// NewMockTransactGateway creates a new mock instance.
func NewMockTransactGateway(ctrl *gomock.Controller) *MockTransactGateway {
	mock := &MockTransactGateway{ctrl: ctrl}
	mock.recorder = &MockTransactGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactGateway) EXPECT() *MockTransactGatewayMockRecorder {
	return m.recorder
}

// BroadcastSignedTx mocks base method.
func (m *MockTransactGateway) BroadcastSignedTx(ctx context.Context, network string, tx types.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastSignedTx", ctx, network, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastSignedTx indicates an expected call of BroadcastSignedTx.
func (mr *MockTransactGatewayMockRecorder) BroadcastSignedTx(ctx, network, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastSignedTx", reflect.TypeOf((*MockTransactGateway)(nil).BroadcastSignedTx), ctx, network, tx)
}

// BuildTransaction mocks base method.
func (m *MockTransactGateway) BuildTransaction(ctx context.Context, network string, input *types.TransferOpts) (types.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildTransaction", ctx, network, input)
	ret0, _ := ret[0].(types.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildTransaction indicates an expected call of BuildTransaction.
func (mr *MockTransactGatewayMockRecorder) BuildTransaction(ctx, network, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTransaction", reflect.TypeOf((*MockTransactGateway)(nil).BuildTransaction), ctx, network, input)
}

// EstimateGas mocks base method.
func (m *MockTransactGateway) EstimateGas(ctx context.Context, network string, input *types.TransferArgs) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGas", ctx, network, input)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGas indicates an expected call of EstimateGas.
func (mr *MockTransactGatewayMockRecorder) EstimateGas(ctx, network, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGas", reflect.TypeOf((*MockTransactGateway)(nil).EstimateGas), ctx, network, input)
}

// GetBalance mocks base method.
func (m *MockTransactGateway) GetBalance(ctx context.Context, network, address string, contractAddress *string) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, network, address, contractAddress)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockTransactGatewayMockRecorder) GetBalance(ctx, network, address, contractAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockTransactGateway)(nil).GetBalance), ctx, network, address, contractAddress)
}
<<<<<<< HEAD

// BuildTransaction mocks base method.
func (m *MockTransactGateway) BuildTransaction(ctx context.Context, network string, input *types.TransferArgs) (types.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildTransaction", ctx, network, input)
	ret0, _ := ret[0].(*types.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildTransaction indicates an expected call of BuildTransaction.
func (mr *MockTransactGatewayMockRecorder) BuildTransaction(ctx, network, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTransaction", reflect.TypeOf((*MockTransactGateway)(nil).BuildTransaction), ctx, network, input)
}
=======
>>>>>>> b682829e0c9170878557e2a7a9535677551d1565
